AllCops:
  Exclude:
    - "bin/**/*"
    - "spec/dummy/**/*"
    - "script/**/*"
    - "db/**/*"

Metrics/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

Metrics/MethodLength: 
  Max: 20

Metrics/ClassLength:
  Max: 1500

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "spec/**/*"

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false