default:
  hubrise_client_id:     'dummy_id'
  hubrise_client_secret: 'dummy_secret'
  hubrise_oauth_host:    'dummy.hubrise.host'
  hubrise_oauth_port:    4003
  hubrise_api_host:      'dummy.hubrise.host'
  hubrise_api_port:      4000
  hubrise_use_https:     false
