name: rubocop

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Rubocop

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Ruby, run bundle install and cache the gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.7
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop
